version: '2'
services:
  myztl2-app:
    image: myztl2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl2-postgresql:5432/myZTL2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  myztl2-postgresql:
    extends:
      file: postgresql.yml
      service: myztl2-postgresql
